### ISSUE TITLE
Code in master can't doesn't allow installation using pip

### ISSUE THREAD

**Issue by jdennes** [campaignmonitor/createsend-python#50] opened 2017-08-03 18:37 UTC
I tried to publish a new release twice, but the code in `master` doesn't allow installation via `pip`:

```
› pip3 install createsend
Collecting createsend
  Downloading createsend-4.2.4.tar.gz (161kB)
    100% |████████████████████████████████| 163kB 3.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9d/glt4w3hn1ng3bp621522kw7h0000gn/T/pip-build-4emdtbbh/createsend/setup.py", line 11, in <module>
        from lib.release import __version__, __author__
    ModuleNotFoundError: No module named 'lib.release'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9d/glt4w3hn1ng3bp621522kw7h0000gn/T/pip-build-4emdtbbh/createsend/
```

I have removed both the bad releases.

I do not have time to resolve this.

Whoever ends up doing it will need to bump the version to 4.2.5 when it's published.

**Comment by djstein** [comment] 2017-08-03 20:23
thanks. I know I passed all the tests on python 3 and python 2 builds. I will make sure I pushed my latest changes!

**Comment by Steffenhvid** [comment] 2017-08-15 07:17
Just for info, on mac the response is a little different:
Collecting createsend
  Using cached createsend-4.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1q/0llk4md57gz4zlv_sp02_9s06w2ff8/T/pip-build-jpmkka95/createsend/setup.py", line 3, in <module>
        from createsend.createsend import __version__
      File "/private/var/folders/1q/0llk4md57gz4zlv_sp02_9s06w2ff8/T/pip-build-jpmkka95/createsend/createsend/__init__.py", line 20, in <module>
        from createsend.version import __version__
    ModuleNotFoundError: No module named 'createsend.version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1q/0llk4md57gz4zlv_sp02_9s06w2ff8/T/pip-build-jpmkka95/createsend/

**Comment by djstein** [comment] 2017-10-25 15:04
duplicate of #45 closing.

**Comment by katharosada** [comment] 2017-10-29 23:43
Fixed in https://github.com/campaignmonitor/createsend-python/commit/d1d545f6e9f85eb1063c64fa2d5d383f844bfe9d

**Closed by katharosada** 2017-10-29 23:43 UTC
